# easydnd developer tasks. Recipe lines must be TAB-indented.

BINARY      := easydnd
MODULE      := github.com/promix1722/easydnd
CMD         := ./cmd/$(BINARY)
BIN_DIR     := bin
SRD_DIR     := data/srd_5.1
DEV_CONFIG  := config.dev.yaml

# Keep in lockstep with the build step in .github/workflows/deploy.yml.
VERSION     ?= $(shell git rev-parse HEAD 2>/dev/null || echo dev)
VERSION_PKG := $(MODULE)/internal/buildinfo
LDFLAGS     := -s -w -X $(VERSION_PKG).Version=$(VERSION)

GOLANGCI_VERSION ?= v2.6.2

# The local Postgres from deploy/local/docker-compose.yml. Production is RDS
# over TLS; this is sslmode=disable because a throwaway container has no CA.
TEST_DATABASE_URL ?= postgres://easydnd:easydnd@127.0.0.1:5433/easydnd?sslmode=disable

# Generated by run/db: config.dev.yaml plus a db.url. Gitignored, never edited
# by hand -- edit config.dev.yaml, or make a config.local.yaml, instead.
DEV_DB_CONFIG := config.dev-db.yaml

.DEFAULT_GOAL := help

## help: list available targets
help:
	@grep -E '^## ' $(MAKEFILE_LIST) | sed 's/^## /  /'

## build/server: build the API binary into bin/
build/server:
	CGO_ENABLED=0 go build -trimpath -ldflags "$(LDFLAGS)" -o $(BIN_DIR)/$(BINARY) $(CMD)

## build/release: build exactly what CI ships (linux/amd64, static)
build/release:
	CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -trimpath -ldflags "$(LDFLAGS)" -o $(BINARY) $(CMD)

## run/server: run the API in development mode
run/server:
	go run -ldflags "$(LDFLAGS)" $(CMD) -config $(DEV_CONFIG)

## test/unit: run the test suite with the race detector
test/unit:
	go test -race ./...

## db/up: start a local Postgres for development and the adapter tests
db/up:
	docker compose -f deploy/local/docker-compose.yml up -d --wait

## db/down: stop the local Postgres and delete its data
db/down:
	docker compose -f deploy/local/docker-compose.yml down -v

## test/db: run the suite against the local Postgres (needs `make db/up`)
# Without TEST_DATABASE_URL the Postgres adapter tests skip, which is what
# keeps `make verify` working on a machine with no Docker. This target is how
# they actually run.
#
# -p 1 because two packages reach the same database and both TRUNCATE it:
# internal/adapter/repository/postgres between subtests, and
# internal/api/http's durability test before it registers. Run in parallel,
# one wipes the other's account mid-test and the failure lands in whichever
# package lost the race -- which is not where the problem is. One database and
# a global TRUNCATE mean the packages have to take turns; only this target
# pays for it, because everywhere else those tests skip.
test/db:
	TEST_DATABASE_URL=$(TEST_DATABASE_URL) go test -race -p 1 ./...

## run/db: run the API in development mode against the local Postgres
# Configuration is a file now, so this writes one: config.dev.yaml plus the
# db.url the container listens on. config.local.yaml wins if you have made one
# (it is gitignored), which is the hook for any other local override.
run/db:
	@if [ -f config.local.yaml ]; then \
	  echo "using config.local.yaml"; \
	  go run -ldflags "$(LDFLAGS)" $(CMD) -config config.local.yaml; \
	else \
	  { cat $(DEV_CONFIG); printf '\ndb:\n  url: %s\n' '$(TEST_DATABASE_URL)'; } > $(DEV_DB_CONFIG); \
	  chmod 600 $(DEV_DB_CONFIG); \
	  echo "wrote $(DEV_DB_CONFIG)"; \
	  go run -ldflags "$(LDFLAGS)" $(CMD) -config $(DEV_DB_CONFIG); \
	fi

## test/cover: run tests and summarise coverage
test/cover:
	go test -race -coverprofile=coverage.out ./...
	go tool cover -func=coverage.out | tail -1

## data/srd: regenerate data/srd_5.1 from the vendored SRD dump
data/srd:
	go run ./cmd/srdgen

## data/srd/check: fail if the committed data differs from srdgen's output
data/srd/check:
	@tmp=$$(mktemp -d); \
	 go run ./cmd/srdgen -out $$tmp >/dev/null || { rm -rf $$tmp; exit 1; }; \
	 if ! diff -rq $(SRD_DIR) $$tmp >/dev/null; then \
	   diff -rq $(SRD_DIR) $$tmp || true; \
	   rm -rf $$tmp; \
	   echo "DATA DRIFT: $(SRD_DIR) does not match srdgen; run 'make data/srd'"; \
	   exit 1; \
	 fi; \
	 rm -rf $$tmp; \
	 echo "srd data current"

## fmt: format all Go source
fmt:
	gofmt -s -w .

## fmt/check: fail if any file is unformatted (mirrors CI)
fmt/check:
	@test -z "$$(gofmt -l .)" || { gofmt -l .; exit 1; }

## vet: run go vet (mirrors CI)
vet:
	go vet ./...

## lint: run golangci-lint without adding it to go.mod
lint:
	go run github.com/golangci/golangci-lint/v2/cmd/golangci-lint@$(GOLANGCI_VERSION) run ./...

## web/deps: install frontend dependencies (clean, lockfile-exact)
web/deps:
	cd web && npm ci

## web/dev: run the Vite dev server; it proxies /v1 to localhost:8080
web/dev:
	cd web && npm run dev

## web/lint: typecheck, lint and layer-check the frontend -- no tests
# Split out from web/check so CI's Check stage can run static analysis without
# paying for the test suite; the Test stage runs web/test.
web/lint:
	cd web && npm run typecheck && npm run lint && npm run lint:layers

## web/test: run the frontend suite once, no watch
web/test:
	cd web && npm run test -- --run

## web/check: typecheck, lint, layer-check and test the frontend (mirrors CI)
web/check: web/lint web/test

## web/build: production build into web/dist
# VITE_APP_VERSION is required -- vite.config.ts refuses to build without it,
# so that a bundle can never ship silently reporting "dev".
web/build:
	cd web && VITE_APP_VERSION=$(VERSION) npm run build

## web/release: build exactly what CI ships to the server
web/release: web/build
	tar -czf web.tar.gz -C web/dist .

## lint/layers: fail if the inner layers reach for transport or storage
lint/layers:
	@! go list -deps ./internal/domain/... ./internal/usecase/... \
	  | grep -E 'gin-gonic|^net/http$$|^database/sql$$|jackc/pgx|pressly/goose' \
	  || { echo "LAYER VIOLATION: inner layers must not import transport or storage"; exit 1; }
	@echo "layers clean"

## tidy: sync go.mod and go.sum
tidy:
	go mod tidy

## verify: everything CI checks, locally
verify: fmt/check vet lint/layers data/srd/check test/unit build/release web/check web/build

## clean: remove build artefacts
clean:
	rm -rf $(BIN_DIR) $(BINARY) coverage.out web.tar.gz web/dist web/dev-dist $(DEV_DB_CONFIG)

.PHONY: help build/server build/release run/server run/db test/unit test/cover \
        db/up db/down test/db \
        data/srd data/srd/check \
        fmt fmt/check vet lint lint/layers tidy verify clean \
        web/deps web/dev web/lint web/test web/check web/build web/release
